Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,145 +5,158 @@ on:
       - master
   
 jobs:
+  
   build_and_test:
       name: build
       uses: ./.github/workflows/build.yml
       secrets: inherit
   
-  security_scan:
-      name: GGshield
-      uses: ./.github/workflows/ggshield.yml
-      secrets: inherit
-    #   continue-on-error: true 
-      
-    # - name: GitGuardian scan
-    #   uses: GitGuardian/ggshield-action@v1.20.0
-    #   env:
-    #       GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
-    #       GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
-    #       GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
-    #       GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
-    #       GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
-    #   continue-on-error: true
+  # security_scan:
+  #     name: GGshield
+  #     uses: ./.github/workflows/ggshield.yml
+  #     secrets: inherit
+  #   #   continue-on-error: true 
+  # Snyk:
+  #     name: Snyk
+  #     uses: ./.github/workflows/Snyk.yml
+  #     secrets: inherit
+  # SBOM:
+  #     name: SBOM
+  #     uses: ./.github/workflows/sbom.yml
+  #     secrets: inherit
+  # Docker_build_push:
+  #     name: docker
+  #     uses: ./.github/workflows/docker.yml
+  #     secrets: inherit
+  # Deployment:
+  #     name: deployment
+  #     uses: ./.github/workflows/deploy.yml
+  #     secrets: inherit
+  #   # - name: GitGuardian scan
+  #   #   uses: GitGuardian/ggshield-action@v1.20.0
+  #   #   env:
+  #   #       GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
+  #   #       GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
+  #   #       GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
+  #   #       GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
+  #   #       GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
+  #   #   continue-on-error: true
 
-    - name: Use Node.js 
-      uses: actions/setup-node@v1
-      with:
-        node-version: 11.x
+    
 
 
-    # - name: Install detect-secrets
-    #   run: pip3 install detect-secrets
-    # - name: detect secret
-    #   run: |
-    #     scan_result=$(detect-secrets scan > scan_result.json)
-    #     if cat "scan_result.json" | grep -q '"hashed_secret":'; then
-    #       echo "Secrets were found during the scan:"
-    #       cat "scan_result.json"
-    #       exit 1
-    #     else
-    #       echo "No secrets were found."
-    #     fi
+  #   # - name: Install detect-secrets
+  #   #   run: pip3 install detect-secrets
+  #   # - name: detect secret
+  #   #   run: |
+  #   #     scan_result=$(detect-secrets scan > scan_result.json)
+  #   #     if cat "scan_result.json" | grep -q '"hashed_secret":'; then
+  #   #       echo "Secrets were found during the scan:"
+  #   #       cat "scan_result.json"
+  #   #       exit 1
+  #   #     else
+  #   #       echo "No secrets were found."
+  #   #     fi
     
     
-    - run: npm install
-    - run: npm run build
-    # - name: Install Snyk CLI
-    #   run: npm install -g snyk@1.1237.0 
+  #   # - run: npm install
+  #   # - run: npm run build
+  #   # - name: Install Snyk CLI
+  #   #   run: npm install -g snyk@1.1237.0 
 
-    # #- name: Authenticate Snyk
-    #   #run: snyk auth ${{ secrets.SNYK_TOKEN }}
+  #   # #- name: Authenticate Snyk
+  #   #   #run: snyk auth ${{ secrets.SNYK_TOKEN }}
 
-    # - name: Run Snyk Test
-    #   run: snyk test --all-projects
-    #   continue-on-error: true
+  #   # - name: Run Snyk Test
+  #   #   run: snyk test --all-projects
+  #   #   continue-on-error: true
         
-    # - name: Check Snyk Test Results
-    #   run: |
-    #       snyk_test_exit_code=$?
-    #       if [ $snyk_test_exit_code -eq 0 ]; then
-    #         echo "Snyk test passed, no vulnerabilities found."
-    #       else
-    #         echo "Snyk test failed, vulnerabilities found."
-    #         exit 1
-    #       fi
-    # - run: npm test 
+  #   # - name: Check Snyk Test Results
+  #   #   run: |
+  #   #       snyk_test_exit_code=$?
+  #   #       if [ $snyk_test_exit_code -eq 0 ]; then
+  #   #         echo "Snyk test passed, no vulnerabilities found."
+  #   #       else
+  #   #         echo "Snyk test failed, vulnerabilities found."
+  #   #         exit 1
+  #   #       fi
+  #   # - run: npm test 
      
-    # - name: Upload artifact for deployment job
-    #   uses: actions/upload-artifact@v2
-    #   with:
-    #     name: deploy_dist
-    #     path: |
-    #         dist
-    #         package.json
+  #   # - name: Upload artifact for deployment job
+  #   #   uses: actions/upload-artifact@v2
+  #   #   with:
+  #   #     name: deploy_dist
+  #   #     path: |
+  #   #         dist
+  #   #         package.json
     
-    - name: Generate SBOM
-      run: |
-          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
-          chmod +x $RUNNER_TEMP/sbom-tool
-          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn Hamritha02/nebular -pv 1.0.0 -ps OwnerName -nsb https://sbom.mycompany.com -V Verbose
+  #   - name: Generate SBOM
+  #     run: |
+  #         curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
+  #         chmod +x $RUNNER_TEMP/sbom-tool
+  #         $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn Hamritha02/nebular -pv 1.0.0 -ps OwnerName -nsb https://sbom.mycompany.com -V Verbose
 
-    - name: Upload SBOM Artifact
-      uses: actions/upload-artifact@v3
-      with:
-          name: sbom
-          path: _manifest/spdx_2.2
-  # Docker_push:
-  #   needs : build_and_test
-  #   runs-on: ubuntu-latest
+  #   - name: Upload SBOM Artifact
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #         name: sbom
+  #         path: _manifest/spdx_2.2
+  # # Docker_push:
+  # #   needs : build_and_test
+  # #   runs-on: ubuntu-latest
     
-  #   steps:
-  #   - name: Checkout
+  # #   steps:
+  # #   - name: Checkout
+  # #     uses: actions/checkout@v3
+  #   - name: Login to DockerHub
+  #     uses: docker/login-action@v2
+  #     with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_TOKEN }}
+  #   - name: Build Container image
+  #     run: docker build -t ${{ secrets.DOCKER_REPO }}:${{ github.run_number }} .
+
+  #   - name: Run Trivy vulnerability scanner
+  #     uses: aquasecurity/trivy-action@master
+  #     with:
+  #         image-ref: '${{ secrets.DOCKER_REPO }}:${{ github.run_number }}'
+  #         format: 'sarif'
+  #         output: 'trivy-results.sarif'
+
+  #   - name: Upload Trivy scan results to GitHub Security tab
+  #     uses: github/codeql-action/upload-sarif@v2
+  #     with:
+  #         sarif_file: 'trivy-results.sarif'
+    
+  #   - name: Publish Docker image
+  #     run: docker push ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
+  # # Deploy:
+  # #   # needs: Docker_push
+  # #   runs-on: ubuntu-latest
+  # #   steps:
+  #   - name: Checkout Repository
   #     uses: actions/checkout@v3
-    - name: Login to DockerHub
-      uses: docker/login-action@v2
-      with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
-    - name: Build Container image
-      run: docker build -t ${{ secrets.DOCKER_REPO }}:${{ github.run_number }} .
-
-    - name: Run Trivy vulnerability scanner
-      uses: aquasecurity/trivy-action@master
-      with:
-          image-ref: '${{ secrets.DOCKER_REPO }}:${{ github.run_number }}'
-          format: 'sarif'
-          output: 'trivy-results.sarif'
-
-    - name: Upload Trivy scan results to GitHub Security tab
-      uses: github/codeql-action/upload-sarif@v2
-      with:
-          sarif_file: 'trivy-results.sarif'
-    
-    - name: Publish Docker image
-      run: docker push ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
-  # Deploy:
-  #   # needs: Docker_push
-  #   runs-on: ubuntu-latest
-  #   steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v3
-      with:
-          repository: Hamritha02/Deployment   # Replace with the repository URL
-          ref: main 
-          token: ${{secrets.PAT_TOKEN }}
+  #     with:
+  #         repository: Hamritha02/Deployment   # Replace with the repository URL
+  #         ref: main 
+  #         token: ${{secrets.PAT_TOKEN }}
    
-    - name: Modify Manifest
-      run: |
-            # Replace the image and tag in the manifest file
-             echo "GitHub SHA: ${{ github.run_number }}"
-             sed -i "s|hamritha817/angular:.*|hamritha817/angular:${{ github.run_number }}|" ./manifest_angular/deployment.yaml
-    - name: Debug - Show Git Status After Changes
-      run: git status
-      shell: bash
+  #   - name: Modify Manifest
+  #     run: |
+  #           # Replace the image and tag in the manifest file
+  #            echo "GitHub SHA: ${{ github.run_number }}"
+  #            sed -i "s|hamritha817/angular:.*|hamritha817/angular:${{ github.run_number }}|" ./manifest_angular/deployment.yaml
+  #   - name: Debug - Show Git Status After Changes
+  #     run: git status
+  #     shell: bash
  
 
-    - name: Commit and Push Change
-      run: |
-            git config --global user.name "Hamritha02"
-            git config --global user.email "hamrithaanand02@gmail.com"
-            git add ./manifest_angular/deployment.yaml
-            git commit -m "Update image tag with github.run no."
-            git push origin main  
-      env:
-          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
+  #   - name: Commit and Push Change
+  #     run: |
+  #           git config --global user.name "Hamritha02"
+  #           git config --global user.email "hamrithaanand02@gmail.com"
+  #           git add ./manifest_angular/deployment.yaml
+  #           git commit -m "Update image tag with github.run no."
+  #           git push origin main  
+  #     env:
+  #         PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
