Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,10 +23,10 @@ jobs:
           GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
       continue-on-error: true
 
-    # - name: Use Node.js 
-    #   uses: actions/setup-node@v1
-    #   with:
-    #     node-version: 12.x
+    - name: Use Node.js 
+      uses: actions/setup-node@v1
+      with:
+        node-version: 12.x
 
 
     # - name: Install detect-secrets
@@ -45,6 +45,25 @@ jobs:
     
     - run: npm install
     - run: npm run build
+    - name: Install Snyk CLI
+      run: npm install -g snyk@1.1237.0 
+
+    - name: Authenticate Snyk
+      run: snyk auth ${{ secrets.SNYK_TOKEN }}
+
+    - name: Run Snyk Test
+      run: snyk test --all-projects
+      continue-on-error : true
+        
+    - name: Check Snyk Test Results
+      run: |
+          snyk_test_exit_code=$?
+          if [ $snyk_test_exit_code -eq 0 ]; then
+            echo "Snyk test passed, no vulnerabilities found."
+          else
+            echo "Snyk test failed, vulnerabilities found."
+            exit 1
+          fi
     - run: npm test 
      
     - name: Upload artifact for deployment job
