Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,37 +45,49 @@ jobs:
     
     - run: npm install
     - run: npm run build
-    - name: Install Snyk CLI
-      run: npm install -g snyk@1.1237.0 
+    # - name: Install Snyk CLI
+    #   run: npm install -g snyk@1.1237.0 
 
-    #- name: Authenticate Snyk
-      #run: snyk auth ${{ secrets.SNYK_TOKEN }}
+    # #- name: Authenticate Snyk
+    #   #run: snyk auth ${{ secrets.SNYK_TOKEN }}
 
-    - name: Run Snyk Test
-      run: snyk test --all-projects
-      continue-on-error: true
+    # - name: Run Snyk Test
+    #   run: snyk test --all-projects
+    #   continue-on-error: true
         
-    - name: Check Snyk Test Results
-      run: |
-          snyk_test_exit_code=$?
-          if [ $snyk_test_exit_code -eq 0 ]; then
-            echo "Snyk test passed, no vulnerabilities found."
-          else
-            echo "Snyk test failed, vulnerabilities found."
-            exit 1
-          fi
-    - run: npm test 
+    # - name: Check Snyk Test Results
+    #   run: |
+    #       snyk_test_exit_code=$?
+    #       if [ $snyk_test_exit_code -eq 0 ]; then
+    #         echo "Snyk test passed, no vulnerabilities found."
+    #       else
+    #         echo "Snyk test failed, vulnerabilities found."
+    #         exit 1
+    #       fi
+    # - run: npm test 
      
-    - name: Upload artifact for deployment job
-      uses: actions/upload-artifact@v2
-      with:
-        name: deploy_dist
-        path: |
-            dist
-            package.json
+    # - name: Upload artifact for deployment job
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: deploy_dist
+    #     path: |
+    #         dist
+    #         package.json
     
    
-  
+    - name: Install OWASP Dependency-Check
+      run: |
+          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.3.2-release.zip
+          unzip dependency-check-6.3.2-release.zip -d /opt
+      
+    - name: Generate SBOM
+      run: /opt/dependency-check/bin/dependency-check.sh --project "My Project" --scan . --format ALL
+
+    - name: Store SBOM as Artifact
+      uses: actions/upload-artifact@v2
+      with:
+          name: sbom
+          path: dependency-check-report
   Docker_push:
     needs : build_and_test
     runs-on: ubuntu-latest
